<a href="https://colab.research.google.com/github/V-Nayak/python-basics/blob/main/18_numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is **NumPy**

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.

There are the following advantages of using NumPy for data analysis.

NumPy performs array-oriented computing.
It efficiently implements the multidimensional arrays.
It performs scientific computations.
It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.
NumPy provides the in-built functions for linear algebra and random number generation

# NumPy Ndarray
Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing. Each element of the Array object contains the same size in the memory.

## Creating a ndarray object
The ndarray object can be created by using the array routine of the numpy module. For this purpose, we need to import the numpy.

In [11]:
import numpy as np
a = np.array
print(a)

<built-in function array>


In [12]:
a = np.array([1,2,4])      ## an array
print(a)

[1 2 4]


In [13]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
a = np.array([[1,2,3],[10,20,30]])   ### creating multi dimensional array
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [17]:
a = np.array([[1,2,3],["a","b","c"],[10,20,30]])   ### creating multi dimensional array
a

array([['1', '2', '3'],
       ['a', 'b', 'c'],
       ['10', '20', '30']], dtype='<U21')

In [18]:
# To change the data type of the array elements, mention the name of the data type along with the collection.
a = np.array([1, 3, 5, 7], complex)  
a

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j])

In [19]:
# To change the data type of the array elements, mention the name of the data type along with the collection.
a = np.array([1, 3, 5, 7], float)  
a


array([1., 3., 5., 7.])